### ISSUE TITLE
Need to use HTTPS now in examples for running the appAuthClient sample

### ISSUE THREAD

**Issue by markcraig** [ForgeRock/exampleOAuth2Clients#10]
_Running the sample_ in the README shows examples with `curl 'http://...`.

With the latest version of the sample platform, I found I need to use `curl --insecure 'https://...` instead to avoid responses like this one:

```
<html>
<head><title>308 Permanent Redirect</title></head>
<body bgcolor="white">
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx/1.15.3</center>
</body>
</html>
```

**Comment by jakefeasel** [comment]
I restarted the sample from scratch and had no such trouble. It's not redirecting me to https... not sure why it is for you. Any idea?

**Comment by markcraig** [comment]
Thanks for testing. I do not know why.

The README has references to 6.0 product components. I think I recall seeing 6.5.0 milestones instead of 6.0 when setting up the platform sample.

**Comment by jakefeasel** [comment]
All samples have been updated to use the latest forgeops / forgeops-init patterns, which include SSL throughout.
