### ISSUE TITLE
Question about multiple app logout (Or a single logout)

### ISSUE THREAD

**Issue by sudhish1** [ForgeRock/exampleOAuth2Clients#80]
We have a scenario where we have app1(spa) navigating to app2 (Spa). The user then decides to logout from app2. Are there any suggestions on how the user can be prompted to login if they hit the backbutton  and go to app1? If there is a better forum to ask this, please let me know. I was reading this : https://developer.forgerock.com/docs/platform/how-tos/building-sso-client-your-rest-apis-oidc and decided I would ask the question here.

**Comment by jakefeasel** [comment]
Take a look at https://github.com/ForgeRock/oidcSessionCheck . You can add this to pretty much any web app, and it will help you with single-logout. If you have any questions or trouble with it, please feel free to follow up with questions in that project. Thanks
